services:
  postgres:
    image: postgres:13
    container_name: motorcycle-postgres
    restart: always
    environment:
      POSTGRES_DB: motorcycle_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - ./db-data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: motorcycle-redis
    restart: always
    ports:
      - '6379:6379'
